### PR TITLE
ちーっす  !

### PR DESCRIPTION
**Pull request by Froxcey**
LMAO

vibe

### CODE REVIEW

**Comment by MrSerge01** [comment]
vibe fail

**Comment by Froxcey** [comment]
Fixed

**Comment by MrSerge01** [comment]
sorry, but i have to decline... :(
i'm already working on removing chiissu ASAP until v0.1 hits.
it's now a virus, i can't do anything about it...
HELP

**Comment by Froxcey** [comment]
k

**Comment by MrSerge01** [comment]
> k

lmao sorry i removed chiissu already

**Pull request closed without merging**
